### ISSUE TITLE
default docker-compose.yaml is panicking on weather

### ISSUE THREAD

**Issue by dhulihan** [flohoss/godash#5]
Hi, this is a cool project! 

I just wanted to note when i plugged in the default vanilla `docker-compose.yaml` and run `docker-compose up`, the application is panicking around weather logic:

```txt
godash  | time="2022/11/04 16:54:59" level=info msg="application running" port=4000
godash  | panic: runtime error: index out of range [0] with length 0
godash  |
godash  | goroutine 6 [running]:
godash  | godash/weather.copyWeatherValues(0xc000200000)
godash  |       /backend/weather/weather.go:39 +0x21f
godash  | godash/weather.updateWeather(0x0?)
godash  |       /backend/weather/weather.go:66 +0x2b5
godash  | created by godash/weather.NewWeatherService
godash  |       /backend/weather/weather.go:22 +0xf1
```

My docker-compose.yaml:

```yaml
version: '3.9'
services:
  godash:
    image: unjxde/godash:latest
    container_name: godash
    restart: unless-stopped
    environment:
      # https://docs.linuxserver.io/general/understanding-puid-and-pgid
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      # can be multiple hosts, comma separated, no spaces
      - ALLOWED_HOSTS=https://home.example.com
      # change title to something else
      - TITLE=GoDash
      # available log-levels: trace,debug,info,warn,error,fatal,panic
      - LOG_LEVEL=info
      # create account here to get free key:
      # https://home.openweathermap.org/users/sign_up
      # remove to disable weather
      - OPEN_WEATHER_KEY=thisIsNoFunctioningKey
      # standard, metric or imperial
      - OPEN_WEATHER_UNITS=metric
      # https://openweathermap.org/current#multi
      - OPEN_WEATHER_LANG=en
      # Temp is normally xx.xx, can be rounded to xx if desired
      - OPEN_WEATHER_DIGITS=true
      # location is needed for weather
      - LOCATION_LATITUDE=48.644929601442485
      - LOCATION_LONGITUDE=9.349618464869025
      # show live system information
      - LIVE_SYSTEM=true
    volumes:
      # to mount the bookmarks.json and the icons folder on the system
      - ./storage:/app/storage
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#ports
    ports:
      - "4000:4000"
```
